### ISSUE TITLE
Windows subsystem JSON issue

### ISSUE THREAD

**Issue by jonathanKingston** [cr/webextaware#20]
My Python isn't good enough to get this working, I managed to sync the info from AMO after finally realising I needed `python3-dev` and `build-essential` but I get this following error:

Traceback (most recent call last):
  File "/home/jonathan/.local/bin/webextaware", line 9, in <module>
    load_entry_point('webextaware==1.2.1', 'console_scripts', 'webextaware')()
  File "/home/jonathan/.local/lib/python3.5/site-packages/webextaware/main.py", line 78, in main
    result = modes.run(args)
  File "/home/jonathan/.local/lib/python3.5/site-packages/webextaware/modes/runmode.py", line 127, in run
    if not current_mode.setup():
  File "/home/jonathan/.local/lib/python3.5/site-packages/webextaware/modes/runmode.py", line 72, in setup
    self.meta = md.Metadata(filename=md.get_metadata_file(self.args))
  File "/home/jonathan/.local/lib/python3.5/site-packages/webextaware/metadata.py", line 30, in __init__
    self.load(filename)
  File "/home/jonathan/.local/lib/python3.5/site-packages/webextaware/metadata.py", line 44, in load
    for e in json.load(f):
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by jonathanKingston** [comment]
This was after running `webextaware query 737717` or just `webextaware`

**Comment by cr** [comment]
Can you try Python 3.6? I have actually never tried it with Python 3.5 and I suspect that the JSON module's data types might have changed.

**Comment by jonathanKingston** [comment]
Should have known Ubuntu having a super outdated version of a language. Checking now.

**Comment by jonathanKingston** [comment]
Got past that hurdle with using 3.6 thanks for that, just grepping all repos now. Everything appears to be working.

**Comment by jonathanKingston** [comment]
Also thanks!
